// =====================================================================
// i2s_controller.sv - I2S controller (CPU/DSP side)
// =====================================================================
// Drives tx_data/tx_valid (CPU sends audio sample to codec), then
// asserts done.  The controller receives BCLK/LRCLK from the
// peripheral (codec) — in this test they are generated by the
// peripheral module.
// =====================================================================
module i2s_controller (
  input  logic       clk,             // system clock
  input  logic       rstn,            // active-low reset
  i2s_if.master      m,               // master modport (bclk/lrclk=input,
                                       //   tx_data/tx_valid=output,
                                       //   rx_data/rx_valid=input)
  output logic       done             // high when test sequence completes
);

  // ---- counter: sends 4 audio samples then stops ------------------
  logic [3:0] cnt = 0;

  always_ff @(posedge clk or negedge rstn) begin
    if (!rstn) begin
      // Reset: clear outputs
      cnt        <= 0;
      m.tx_valid <= 0;
      m.tx_data  <= 0;
    end else if (cnt < 4) begin
      // Drive audio sample to the codec
      m.tx_data  <= 24'hA5A5A5;        // test sample pattern
      m.tx_valid <= 1;                 // strobe valid
      cnt        <= cnt + 1;
    end else begin
      // Sequence done
      m.tx_valid <= 0;
      done       <= 1;
    end
  end

endmodule
